docker_registry: ENC[AES256_GCM,data:y40PWP5rgEr7MmCOalc=,iv:DrP27pOTmVM02Mue3NxgJM7n9bT4Mp8J/CM6GGkW+Hg=,tag:Yga+28pcmi1Vgp59gliiOw==,type:str]
sops:
    age:
        - recipient: age1lru73g2m2y9zydfsdlfgvda7xw8qnhwepaydnheq3l6xal4pvqfslr5vht
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFKzQ3ZXlDK2pCcmhGZUJP
            a1ZmcnZybTBrNXB2LzVCT3BnaDVDb1VTN2wwCmhTVFZIbkhsd1ljVm9ZWkdGdHNz
            bEtYb0xubC95ZkhoOWNQcUVFRVdGWk0KLS0tIE13UzdBNEZrRExEQjV3eU05N1FN
            NkdhRTV5b1h0U1plamlSbDU3RFRvNncKg9S+ccg5mrKRE5umj1rS+EPzUCJbgM/x
            +tnuxkrJvjZqNMotfrYNnFjGoQYWgvcLJZPvcfjhQ/geEE3r1Wkeew==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1m4v0egh4e94qcns0se3088zdshvp4xurz3gs4pxqk3p60clm85eqgn3j2n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWlp5NUp2Wis5dWNoWmNE
            dWQ3R2diRDIwSjZSZEF3dGY3WCtiTFZwOEc4CmF5ZGYydUovT2JIQmtiS2QxdUda
            aUxsTzBvcm1zYUlTcng2ampKZDRZcXcKLS0tIG10dStEQUxVNkNTdndpdEJnN3Zj
            ZWxqMWhpNEhrMlJjQ0dOazhjYUdRNG8KdcnZEkO+Tz09NYOA0Ztt6xQA6AfuwpY+
            82AH8mPyBXCwbeUjSSiHjqOvGOjtavS9HCEpQl6nT58zXfNr6/BLMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T16:38:37Z"
    mac: ENC[AES256_GCM,data:O1y7JV7RI8JfQgQPK3SpAN+u+y7P7aEomd8R/AKgeqENfCbKAiqTdBqb7iEDZneTYTCY8tP0bbB+oGipawmZ21vUOEH+RfXavaiaWJYAzJDD6WX3aZJ0ozDwPqXf5vNHpp9cdiUmdRKNsTaRFrwWEcH9hPmgtKvBlTlvqUsr0SI=,iv:gQ9yaWjeSKF2iBAsGH/wQ/DAV4ubYMAKeCDVtSBTr1U=,tag:IqPjs+nvQNHnvx2vq78vxQ==,type:str]
    encrypted_regex: .*
    version: 3.11.0
