version: '3'

tasks:
  default:
    cmds:
      - task -l

  vault:*:*:
    desc: "Ansible vault wrapper. Example: task vault:edit:host_vars/prod/secrets.yml"
    vars:
      COMMAND: "{{ index .MATCH 0 }}"
      PATH: "{{ index .MATCH 1 }}"
    dir: ansible
    cmds:
      - ansible-vault {{.COMMAND}} {{.PATH}}

  ansible:provision-server:
    desc: "Provision remote production server"
    dir: ansible
    cmds:
      - ansible-playbook playbooks/provision-server.yaml

  ansible:deploy:
    desc: "Deploy"
    dir: ansible
    cmds:
      - ansible-playbook playbooks/deploy.yaml

  ansible:deploy-local:
    desc: "Deploy local"
    dir: ansible
    cmds:
      - ansible-playbook playbooks/deploy-local.yaml

  compose:up:
    desc: "Start Docker Compose stack"
    dir: compose
    cmds:
      - docker compose up -d --build

  compose:down:
    desc: "Stop Docker Compose stack"
    dir: compose
    cmds:
      - docker compose down

  compose:ps:
    desc: "Show Docker Compose services status"
    dir: compose
    cmds:
      - docker compose ps
