set dotenv-load := true

set shell := ["/bin/bash", "-c"]

# list of all justfile recipes
default:
    just --list --unsorted

# run command in local docker image
local *args:
    docker run --rm -it \
    -v ${MOUNT} -w /app \
    -e SSH_PRIVATE_KEY \
    ${IMAGE} \
    bash -c 'mkdir -p ~/.ssh && \
    echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_ed25519 && \
    chmod 600 ~/.ssh/id_ed25519 && \
    echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config && \
    just {{args}}'

# manipulate vault files
vault-file command path:
    ansible-vault {{command}} {{path}} --vault-password-file .ansible_vault

# configure server
configure-server:
    ansible-playbook -i inventory.yaml playbooks/configure-server.yaml --vault-pass-file .ansible_vault

